Update modules.py
Zaktualizowano; return_complex=True

/usr/local/lib/python3.10/dist-packages/torch/functional.py in stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided, return_complex)
    648 
    649 [1] D. W. Griffin and J. S. Lim, "Signal estimation from modified short-time Fourier transform,"
--> 650 IEEE Trans. ASSP, vol.32, no.2, pp.236-243, Apr. 1984.
    651 
    652 Args:

RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.